# How to use :
# export PUID=$(id -u)
# export PGID=$(id -g)
# docker-compose up -d
# docker-compose down
# --------------------------------------------------------------------------------

version: '3'
services:

  torrent:
    hostname: TORRENT
    container_name: docker_torrent
    build: 
      context: ./torrent
      dockerfile: Dockerfile
    volumes:
      - ./downloads/:/downloads/
    ports:
      - "8088:8088"
      - "9000:9000"
      - "8081:8081"
      - "8081:8081/udp"
    networks: 
      vpn:
        ipv4_address: 172.168.21.3
    restart: always


  filebrowser:
    hostname: FILEBROWSER
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - /usr/local/qBitTorrent-docker/downloads:/srv
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 9090:80
    networks: 
      vpn:
        ipv4_address: 172.168.21.4
    restart: always


networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.21.0/24
          gateway: 172.168.21.1
    
